config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian'].freeze
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = (0..5).freeze
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: { in: RATING }
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all.where(restaurant_id: params[:restaurant_id])
  end
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="header">
      <%= link_to "All restaurants", restaurants_path, class: "link-main" %>
      <%= link_to "Create a restaurant", new_restaurant_path, class: "link-main" %>
    </div>

    <%= yield %>
  </body>

</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for  %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="container-list">
    <ul>
      <% @restaurants.each do |restaurant| %>
        <li>
          <h1><%= link_to restaurant.name, restaurant_path(restaurant) %></h1>
          <h2><%= restaurant.category %> cuisine</h2>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f|  %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant::CATEGORIES  %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="container-list">
    <div class="container-content-padding">
      <h1><%= @restaurant.name %></h1>
      <h2><%= @restaurant.address %></h2>
      <h2><%= @restaurant.category %></h2>
    </div>
    <%= link_to "Restaurant reviews", restaurant_reviews_path(@restaurant) %>
  </div>
  <%= link_to "Back to Restaurants", restaurants_path %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<ul>
  <% @reviews.each do |review| %>
  <li>
    <p>Review: <%= review.content %></p>
    <p>Rating: <%= review.rating %></p>
  </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f|  %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>